### ISSUE TITLE
Unable to retrieve antiSMASH annotations 

### ISSUE THREAD

**Issue by jessicaDh** [Yasas1994/MGnify-assembly-downloader#1]
Hello, I hope you're doing well. We're currently using the code found at https://github.com/Yasas1994/MGnify-assembly-downloader to fetch antiSMASH annotations for specific assembly IDs. However, rather than obtaining GenBank (GBK) files as intended, it's fetching FASTA . The command we're employing is: python download_assemblies.py -i analyses_and_assembly.txt -d 17 
We would greatly appreciate your assistance with this matter, as it has a significant impact on our project.

**Comment by Yasas1994** [comment]
Hi,
Thanks for pointing out the bug. I think your issue is fixed now.
